In [1]:
!pip install numpy

In [2]:
import numpy

In [5]:
import numpy as np

In [8]:
matriz_edad=np.array([range(3,29)])
matriz_edad

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [9]:
matriz_edad

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [18]:
matriz_arreglo=np.array([0,1,2,3,4,0,1,2,3,4])
matriz_arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [19]:
matriz_arreglo.sort()
matriz_arreglo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])